mode: classification  # classification or regression
seed: 42
epochs: 20
batch_size: 8
learning_rate: 1.0e-4
data_path: pcr_ngs_mapper/data/synthetic_pcr_ngs_dataset.csv
model_dir: models
results_dir: results
num_workers: 0
